### ISSUE TITLE
UX issue: content placement and alignment

### ISSUE THREAD

**Issue by itsbirdo** [hero-org/herocast#210]
left aligned content is quite odd when I feel the majority of my web experience is with centered content. 
This is particularly noticible when using a ultra wide monitor. 
Consider changing to centered content or having the option to change it

**Comment by itsbirdo** [comment]
Twitter:
<img width="2333" alt="image" src="https://github.com/hellno/herocast/assets/93915849/ce0c0852-f10f-4211-817a-5949884a3649">


herocast: 
<img width="2329" alt="image" src="https://github.com/hellno/herocast/assets/93915849/4840ce32-0e25-4734-9346-f2f634ce748a">

**Comment by scottrepreneur** [comment]
Yeah centering these + matching the individual cast view page would help a ton with this feeling more fluid I think!

**Comment by hellno** [comment]
@scottrepreneur I'm not 100% sure how to go about this. do you have a recommendation? I assume we just set a global max width in `pags/home/index.tsx` and center it there?

**Comment by hellno** [comment]
solved by #461
