### ISSUE TITLE
UX: Clicking username/profile card navigates to feed

### ISSUE THREAD

**Issue by scottrepreneur** [hero-org/herocast#230]
Clicking the user's name or profile card opens a new tab with the following feed again. Can we disable this click behavior if there's no profile page for users yet?

<img width="563" alt="Screenshot 2024-04-25 at 08 12 53" src="https://github.com/hellno/herocast/assets/1778380/41c16d09-5254-4faf-a1f5-0a3c99328626">

**Comment by hellno** [comment]
temporarily fixed this by not forwarding to herocast profile pages and instead falling back to Warpcast
