### ISSUE TITLE
Clicking reply activates recast

### ISSUE THREAD

**Issue by scottrepreneur** [hero-org/herocast#277]
Pretty sure this is a new regression

<img width="137" alt="Screenshot 2024-05-20 at 08 03 42" src="https://github.com/hellno/herocast/assets/1778380/7e3978c0-6264-4373-a8c4-1ab4bdbcae56">

After click reply icon:
<img width="174" alt="Screenshot 2024-05-20 at 08 05 00" src="https://github.com/hellno/herocast/assets/1778380/27f2a58f-ef6f-4e8e-b667-38809c25d5a4">

**Comment by hellno** [comment]
fixed in #305
