### ISSUE TITLE
Allow user to toggle between accounts while replying

### ISSUE THREAD

**Issue by scottrepreneur** [hero-org/herocast#278]
ignore really bad draws

dropdown with alternate account
<img width="616" alt="Screenshot 2024-05-20 at 08 03 32" src="https://github.com/hellno/herocast/assets/1778380/5e1d909a-7ebb-42a6-a70a-8b6e5836e96f">

**Comment by hellno** [comment]
awesome idea! you can only toggle with keyboard shortcuts right now, but should be visible in UI as well :)

**Comment by hellno** [comment]
this is live now
