### ISSUE TITLE
Copy edit: headline in channels

### ISSUE THREAD

**Issue by bijanfarsijani** [hero-org/herocast#317]
In Channel the first headline says

Pinned Channels. What is missing is context why is should pin. Add subline:
Pinned channels appear in your feeds

![Screenshot 2024-06-06 at 17 17 43](https://uploads.linear.app/62a11748-495a-4507-ae9b-b9aff59831d1/f58ff07b-278d-41bc-a7b0-c0e297b98954/8e41331a-b7b0-42b0-a2f2-83612eb589bf?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzYyYTExNzQ4LTQ5NWEtNDUwNy1hZTliLWI5YWZmNTk4MzFkMS9mNThmZjA3Yi0yNzhkLTQxYmMtYTdiMC1jMGUyOTdiOTg5NTQvOGU0MTMzMWEtYjdiMC00MmIwLWEyZjItODM2MTJlYjU4OWJmIiwiaWF0IjoxNzE3Njg5Nzk1LCJleHAiOjMzMjg4MjQ5Nzk1fQ.XL438OTBjlTRFoNn7CqD8mOz63bRT2JNjaM8pe3RdJw "=1292x")

**Comment by hellno** [comment]
fixed
