### ISSUE TITLE
Channel: remove side bar

### ISSUE THREAD

**Issue by bijanfarsijani** [hero-org/herocast#318]
The sidebar in Channels is confusing. When I click on manage nothing happens. Let's hide it until we find other use for this space.

![Screenshot 2024-06-06 at 17 20 48](https://uploads.linear.app/62a11748-495a-4507-ae9b-b9aff59831d1/e2bc84d2-83b5-4004-b0c1-7d10d971608f/9a72ef5c-8929-4490-abc5-46d2b1b3f930?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzYyYTExNzQ4LTQ5NWEtNDUwNy1hZTliLWI5YWZmNTk4MzFkMS9lMmJjODRkMi04M2I1LTQwMDQtYjBjMS03ZDEwZDk3MTYwOGYvOWE3MmVmNWMtODkyOS00NDkwLWFiYzUtNDZkMmIxYjNmOTMwIiwiaWF0IjoxNzE3Njg5Nzc5LCJleHAiOjMzMjg4MjQ5Nzc5fQ.JY3k2tG5mAfNhGA-UnGbl2oudbT2LKNa47XrCta4H1k "=1436x")

**Comment by hellno** [comment]
fixed
