### ISSUE TITLE
Improve channels search & dropdown

### ISSUE THREAD

**Issue by bijanfarsijani** [hero-org/herocast#369]
show size( followers numbers) next to channels in Channel Search 
<img width="1306" alt="Screenshot 2024-06-24 at 15 45 25" src="https://github.com/hero-org/herocast/assets/110478997/bf55e135-46a7-44a0-a6b0-f56186e13a3d">

& on dropdown in posts
<img width="1112" alt="Screenshot 2024-06-24 at 15 46 31" src="https://github.com/hero-org/herocast/assets/110478997/4f05caf3-c498-4259-95cf-e78294ef083d">

make search sensitive to channel handle ("fwb") and not only name ("friends with benefits") example: https://warpcast.com/~/channel/fwb

make search insensitive to spaces in a way to that "higher" and "higher " lead to valid. Currently only the former leads to the wished result

<img width="1355" alt="Screenshot 2024-06-24 at 15 57 05" src="https://github.com/hero-org/herocast/assets/110478997/254a7d8c-3d55-4da6-807a-ea711aac32aa">

**Comment by hellno** [comment]
<img width="476" alt="image" src="https://github.com/hero-org/herocast/assets/686075/e12c5013-28dd-4cb3-adff-211caa012fd4">
