### ISSUE TITLE
Add list of recent unfollows to analytics

### ISSUE THREAD

**Issue by hellno** [hero-org/herocast#455]
**Is your feature request related to a problem? Please describe.**
Analytics page (on /analytics url) currently shows follows, reactions and recent top casts.
We want to add a new table that shows who and when someone recently unfollowed. 

**Describe the solution you'd like**
The supabase function `create-analytics-data`, powered by Deno, runs queries on the DB that stores the Farcaster activity data. Query example function: `getCastsOverview`, generates a list of recent casts. This is a different DB than the supabase DB which manages: user data, Farcaster account connections, channels, etc.

the flow is
- in supabase function:
  - query data from Farcaster activity DB
  - organize into data structure that we want to use later
  - store in supabase DB `analytics` table
- analytics page:
  - only has to query supabase analytics table by FID (Farcaster ID) that the user wants to see
  - show all data that we have in graphs and tables 

two code places are relevant for this:
- supabase functions directory to create the data points and save themhttps://github.com/hero-org/herocast/tree/5e61abc1a58fc61588795fa16e2e0c509cf4c1fb/supabase/functions
spread over the `create-analytics-data` folder as well as `_shared`
- Analytics page https://github.com/hero-org/herocast/blob/main/pages/analytics/index.tsx with components to render  

**Additional context**
- supabase functions: https://supabase.com/docs/guides/functions/quickstart
- UI: we can just add another table below the top casts for now. We'll improve the navigation across all the new graphs and tables on the page later

<img width="1084" alt="image" src="https://github.com/user-attachments/assets/2a0ea489-69d0-4aea-9154-e54e8704eeca">.

**Comment by hellno** [comment]
@dragmakex fyi

**Comment by dragmakex** [comment]
Thanks, will look into it :)

**Comment by dragmakex** [comment]
https://github.com/hero-org/herocast/pull/513
