### ISSUE TITLE
make all "new draft" boxes the same

### ISSUE THREAD

**Issue by bijanfarsijani** [hero-org/herocast#467]
<img width="762" alt="Screenshot 2024-08-14 at 17 21 09" src="https://github.com/user-attachments/assets/fffc7199-cf10-485a-aa5a-ec9ec3d75d7d">
<img width="744" alt="Screenshot 2024-08-14 at 17 21 18" src="https://github.com/user-attachments/assets/72899603-2940-49d5-be7b-2b3994681fcc">

**Comment by hellno** [comment]
fixed in #482
